### ISSUE TITLE
Problem with using raw data observations in evaluate.R script

### ISSUE THREAD

**Issue by Dekermanjian** [cuamc-dop-ids/hptbi-hackathon#2]
@dewittpe 
The evaluate.R script uses the raw observed outcomes to check against predictions. However, predictions on either training or testing sets are derived from processed data, where observations may have been omitted due to missing values that are present in the feature/predictor columns of the data. This will result in predictions being a different length than the raw observations and the predictions won't align with the true outcome values (index-wise). I think that the true observations of the testing/training sets should be pulled out in the testing.R/pr scripts after the prepare data functions are executed and written as a .txt file that are then read into the evaluate.R script.

**Comment by dewittpe** [comment]
The choice to check against _all_ observations was deliberate.  One of the challenges for hackathon participants is to handle missing data in the variables.  The data_dictionary.md file includes information on missing data in the training and testing sets.

Justifications for forcing handling missing data: 

* missing values _might_ be informative,
* a model used during a patient's hospitalization will need to be able to provide a prediction in the presence of missing data.

**Comment by Dekermanjian** [comment]
@dewittpe 
Understood. However, the processing that you employ on the fss training data, within prepare_fss, omits 49 observations from the raw data. Is that accounted for somehow?

**Comment by dewittpe** [comment]
> @dewittpe
> Understood. However, the processing that you employ on the fss training data, within prepare_fss, omits 49 observations from the raw data. Is that accounted for somehow?

Yes.  In evaluate.R the observed FSS data omits missing FSS data.  See https://github.com/cuamc-dop-ids/hptbi-hackathon/blob/54d4f22fab88549e399b373d21bb043dae8a16d2/evaluate.R#L20-L38

Dealing with missing data in features/predictors is a part of the hackathon.  With the objective of estimating FSS as an integer value we are forced to consider only rows where the FSS is known for assessment.

**Comment by Dekermanjian** [comment]
@dewittpe 
Great! Thank you.
